# Generated by Django 4.1.10 on 2023-08-09 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Biometric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("weight_morning", models.FloatField(blank=True, null=True)),
                ("weight_after_run", models.FloatField(blank=True, null=True)),
                ("weight_night", models.FloatField(blank=True, null=True)),
                ("heart_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "systolic_pressure",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "diastolic_pressure",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
