# Generated by Django 4.1.10 on 2023-07-26 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("running_log", "0002_run_pace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="pace",
        ),
    ]
