# Generated by Django 4.1.10 on 2023-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("running_log", "0004_run_pace"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="duration_hours",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="duration_minutes",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="duration_seconds",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
