# Generated by Django 4.1.10 on 2023-11-19 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("running_log", "0005_run_duration_hours_run_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="run",
            name="duration_hours",
        ),
        migrations.RemoveField(
            model_name="run",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="run",
            name="duration_seconds",
        ),
    ]
