# Generated by Django 4.1.10 on 2023-11-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("running_log", "0006_remove_run_duration_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="total_time",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
